In [1]:
import numpy as np

In [3]:
arreglo_cero_diez = np.arange(11) ** 2 # Elevar al cuadrado
arreglo_cero_diez

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [4]:
arreglo_cero_diez[5:8] # A pesar de que no es una list, 
## la forma de filtrar de un list funciona aqui

array([25, 36, 49], dtype=int32)

In [9]:
## num pares desde el final hasta el principio
arreglo_cero_diez[::2] ## principio final, num_saltos
arreglo_cero_diez[::-2]

array([  0,   4,  16,  36,  64, 100], dtype=int32)