In [1]:
# NUMPY
# pip install numpy
import numpy as np

In [2]:
print(type((1,2,3)))
print(type([1,2,3]))
print(type(np.array((1,2,3))))
print(type(np.array([1,2,3])))

<class 'tuple'>
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### Matriz/Arreglo de Ceros

In [4]:
np.zeros([5])
np.zeros((1))

array([0.])

In [7]:
np.zeros([2,2])  # fila, columna, elementos array (3ra dimensión xdxd)

array([[0., 0.],
       [0., 0.]])

### Matriz/Arreglo de Unos

In [8]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Matriz Diagonal

In [9]:
np.eye(4)  # Matriz cuadrada

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Generar Arrays Numéricos

In [10]:
np.arange(12) # Arreglo de 12 numeros (empieza desde el 0 hasta el 12 - 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
np.arange(4,20) # El mismo arreglo solo que se da el rango [4,2)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(-2,1) # Array de numeros negativos [-2,1)

array([-2, -1,  0])

In [27]:
arreglo_pares = np.arange(0,20,2) # El tercer parámetro indica los saltos

In [21]:
print(arreglo_pares.size)
print(len(arreglo_pares))

4
4


In [25]:
arreglo_tres_dimensiones = np.zeros((2,3,4))
print(arreglo_tres_dimensiones.shape)  # Retorna dimensiones

(2, 3, 4)


In [31]:
# Reshape --> redimensionar matriz/array
arreglo_pares.reshape(5,2) # Los numeros deben multiplicar al total de los elementos del array
arreglo_pares.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [48]:
array_24 = np.arange(24)
array_24.reshape(6,4)
array_24.reshape(4,6)
array_24.reshape(8,3)
array_24.reshape(3,8)
array_24.reshape(2,12)
array_24.reshape(12,2)
array_24.reshape(6,2,2)
array_24.reshape(2,6,2)
array_24.reshape(2,2,6)
array_24.reshape(3,2,4)
array_24.reshape(2,3,4)
array_24.reshape(4,3,2)
array_24.reshape(4,2,3)
array_24.reshape(3,4,2)
array_24.reshape(2,4,3)
array_24.reshape(2,2,3,2)
array_24.reshape(2,2,2,3)

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]],


       [[[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]]])

### Operaciones con arrays

In [80]:
a = np.array([10,10,10])
b = np.array([5,5,5])
a + b  # suma
a - b  # resta
a * b  # multiplicación
a / b  # división
a % b  # modulo
 # operaciones
a * 10 
a + 7 
a - 8
a / 2
a % 3

array([1, 1, 1], dtype=int32)

In [109]:
# Para operaciones de matrices ambas deben ser de la misma dimensión
matriz_uno = np.arange(-20,20,2).reshape(5,2,2)
print(matriz_uno)
matriz_dos = np.arange(-30,30,3).reshape(5,2,2)
print(matriz_dos)
#  matriz_uno % matriz_dos

[[[-20 -18]
  [-16 -14]]

 [[-12 -10]
  [ -8  -6]]

 [[ -4  -2]
  [  0   2]]

 [[  4   6]
  [  8  10]]

 [[ 12  14]
  [ 16  18]]]
[[[-30 -27]
  [-24 -21]]

 [[-18 -15]
  [-12  -9]]

 [[ -6  -3]
  [  0   3]]

 [[  6   9]
  [ 12  15]]

 [[ 18  21]
  [ 24  27]]]


In [114]:
arreglo_muestra = np.arange(20). reshape(5,2,2)
## devuelve un arreglo de booleanos 
# indicando si el elemento en esa posición cumplió la condicion
condicion_menor = arreglo_muestra > 5
condicion_mayor = arreglo_muestra < 12
condicion_par = arreglo_muestra % 2 == 0
condicion = condicion_menor & condicion_mayor & condicion_par
arreglo_muestra[condicion]

array([ 6,  8, 10])

In [117]:
A = np.arange(4).reshape((2,2))
B = np.arange(4,8).reshape((2,2))
# Producto punto
A.dot(B)
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [122]:
arreglo_doce = np.arange(12)
arreglo_doce.sum()  # Suma de todo los elementos del arreglo
arreglo_doce.min()  # Elemento minimo
arreglo_doce.max()  # Elemento maximo

11

In [138]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [135]:
arreglo_doce.reshape(3,2,2).sum(axis=1)
# Suma en vertical

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [136]:
arreglo_doce.reshape(3,2,2).sum(axis=0)

array([[12, 15],
       [18, 21]])

In [137]:
arreglo_doce.reshape(3,2,2).sum(axis=2)
# Suma de los vectores en h

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])